name             'scm_encrypt'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures scm_encrypt'
long_description 'Installs/Configures scm_encrypt'
version          '0.1.0'
